#[cfg(target_os = "windows")]
pub const PLAYER_POSSIBLE_PATHS: [&str; 32] = [
    "mpv",
    r"C:\Program Files\mpv\mpv.exe",
    r"C:\Program Files (x86)\mpv\mpv.exe",
    r"C:\mpv\mpv.exe",
    r"C:\tools\mpv\mpv.exe",
    r"C:\ProgramData\chocolatey\bin\mpv.exe",
    r"C:\ProgramData\chocolatey\lib\mpv\tools\mpv.exe",
    r"%USERPROFILE%\scoop\apps\mpv\current\mpv.exe",
    r"%USERPROFILE%\scoop\shims\mpv.exe",
    r"C:\ProgramData\scoop\apps\mpv\current\mpv.exe",
    r"C:\ProgramData\scoop\shims\mpv.exe",
    r"%LOCALAPPDATA%\Microsoft\WinGet\Links\mpv.exe",
    r"C:\msys64\mingw64\bin\mpv.exe",
    r"C:\msys64\ucrt64\bin\mpv.exe",
    r"C:\cygwin64\bin\mpv.exe",
    r"C:\Program Files\mpv.net\mpvnet.exe",
    r"C:\Program Files (x86)\mpv.net\mpvnet.exe",
    r"%LOCALAPPDATA%\Programs\mpv.net\mpvnet.exe",
    r"%USERPROFILE%\scoop\apps\mpv.net\current\mpvnet.exe",
    r"%USERPROFILE%\scoop\shims\mpvnet.exe",
    r"C:\ProgramData\chocolatey\bin\mpvnet.exe",
    r"%LOCALAPPDATA%\Microsoft\WinGet\Links\mpvnet.exe",
    r"C:\Program Files\VideoLAN\VLC\vlc.exe",
    r"C:\Program Files (x86)\VideoLAN\VLC\vlc.exe",
    r"%LOCALAPPDATA%\Programs\VideoLAN\VLC\vlc.exe",
    r"C:\ProgramData\chocolatey\bin\vlc.exe",
    r"C:\ProgramData\chocolatey\lib\vlc\tools\vlc.exe",
    r"%USERPROFILE%\scoop\apps\vlc\current\vlc.exe",
    r"%USERPROFILE%\scoop\shims\vlc.exe",
    r"C:\ProgramData\scoop\apps\vlc\current\vlc.exe",
    r"C:\ProgramData\scoop\shims\vlc.exe",
    r"%LOCALAPPDATA%\Microsoft\WinGet\Links\vlc.exe",
];

#[cfg(target_os = "linux")]
pub const PLAYER_POSSIBLE_PATHS: [&str; 31] = [
    "mpv",
    "/usr/bin/mpv",
    "/usr/local/bin/mpv",
    "/bin/mpv",
    "/snap/bin/mpv",
    "/var/lib/flatpak/exports/bin/io.mpv.Mpv",
    "~/.local/share/flatpak/exports/bin/io.mpv.Mpv",
    "~/.local/bin/mpv",
    "/home/linuxbrew/.linuxbrew/bin/mpv",
    "~/.linuxbrew/bin/mpv",
    "/opt/mpv/mpv",
    "/usr/games/mpv",
    "~/.nix-profile/bin/mpv",
    "/nix/var/nix/profiles/default/bin/mpv",
    "/run/current-system/sw/bin/mpv",
    "/usr/pkg/bin/mpv",
    "/usr/bin/vlc",
    "/usr/local/bin/vlc",
    "/bin/vlc",
    "/snap/bin/vlc",
    "/var/lib/flatpak/exports/bin/org.videolan.VLC",
    "~/.local/share/flatpak/exports/bin/org.videolan.VLC",
    "~/.local/bin/vlc",
    "/home/linuxbrew/.linuxbrew/bin/vlc",
    "~/.linuxbrew/bin/vlc",
    "/opt/vlc/vlc",
    "/opt/vlc/bin/vlc",
    "~/.nix-profile/bin/vlc",
    "/nix/var/nix/profiles/default/bin/vlc",
    "/run/current-system/sw/bin/vlc",
    "/usr/pkg/bin/vlc",
];

#[cfg(target_os = "macos")]
pub const PLAYER_POSSIBLE_PATHS: [&str; 23] = [
    "/opt/homebrew/bin/mpv",
    "/usr/local/bin/mpv",
    "/opt/local/bin/mpv",
    "/sw/bin/mpv",
    "/opt/pkg/bin/mpv",
    "/Applications/mpv.app/Contents/MacOS/mpv",
    "~/Applications/mpv.app/Contents/MacOS/mpv",
    "~/.nix-profile/bin/mpv",
    "/nix/var/nix/profiles/default/bin/mpv",
    "/usr/bin/mpv",
    "~/.local/bin/mpv",
    "/Applications/IINA.app/Contents/MacOS/iina-cli",
    "~/Applications/IINA.app/Contents/MacOS/iina-cli",
    "/usr/local/bin/iina",
    "/opt/homebrew/bin/iina",
    "/Applications/VLC.app/Contents/MacOS/VLC",
    "~/Applications/VLC.app/Contents/MacOS/VLC",
    "/opt/homebrew/bin/vlc",
    "/usr/local/bin/vlc",
    "/opt/local/bin/vlc",
    "/opt/pkg/bin/vlc",
    "~/.nix-profile/bin/vlc",
    "/nix/var/nix/profiles/default/bin/vlc",
];
